# Плагин LobbyMaster! Плагин позволяет настраивать различные функции на сервере Лобби.
# Аргументы: true - запрет включен, false - запрет выключен, пустое поле(как-то так: "") - null.
# lobbymaster.admin - отменяет действия пунктов(Break, Place, Chat, Commands), дает Fly, дает доступ к команде /LobbyMaster или /lm
# Написал: vk.com/l1ratch

## БАЗОВЫЕ НАСТРОЙКИ
IceMelt: false # запрет таяния
Damage: false # запрет урона
Hunger: false # запрет голода
Explosions: false # Запрет взрывов
Break: false # запрет ломания блоков
Place: false # запрет установки блоков
Fire: false # запрет распространения огня и сгорания блоков
GameMode: null # установка режима игры (ADVENTURE - приключения, SURVIVAL - выживание, CREATIVE - креатив, null - отключение функции)
Weather: false # запрет погоды

## НАСТРОЙКА СООБЩЕНИЙ О ВХОДЕ/ВЫХОДЕ/СМЕРТИ ИГРОКА (%player% - ник игрока)
StartMessage:
  Allow: false # true - кастомное сообщение или отключение, false - стандартное сообщение

  #(Замены: %player% - никнейм игрока, null - отключает сообщение)
  joinM: "%player% &cзашел! &b(Изменить можно в plugins/LobbyMaster/config.yml)" #Текст входа игрока
  quitM: "%player% &cвышел! &b(Изменить можно в plugins/LobbyMaster/config.yml)" #Текст выхода игрока
  deathM: "%player% &cпогиб! &b(Изменить можно в plugins/LobbyMaster/config.yml)" #Текст смерти игрока

## НАСТРОЙКИ ЧАТА/КОМАНД
Chat: false # отключает чат
Commands: false # отключает возможность писать команды (исключения указывать тут: allow_cmd: )
NoChatText: "&cВы не можете писать в чат! &b(Изменить можно в plugins/LobbyMaster/config.yml)" # Текст, который пишет плагин при попытке написать в чат (работает только когда Chat: true)
NoCommandsText: "&cВы не можете писать в чат! &b(Изменить можно в plugins/LobbyMaster/config.yml)" # Текст, который пишет плагин при попытке выполнить команду (Commands: true)
allow_cmd: #Команды которые можно писать при Commands: true
  - 'skins'
  - 'skin'
  - 'reg'
  - 'register'
  - 'l'
  - 'login'
  - 'cp'
  - 'changepassword'
  - 'menu'

## НАСТРОЙКА ЭФФЕКТОВ
giveInvisibility: false # выдача эффекта невидимости при заходе
giveJump: false # выдача эффекта прыгучести при заходе
giveSpeed: false # выдача эффекта скорости при заходе
BlindNess: false # выдача эффекта слепоты при заходе

## НАСТРОЙКА МИРА
Time:
  Allow: false # Зафиксировать время в мире
  SetTime: 15000 # Значение на котором зафиксировать
  #Значение meaning: 0 - День
  #Значение meaning: 15000 - Ночь

Spawn:
  Allow: false # Если true - при входе игрок оказывается в точке спавна(ниже)
  location: # Координаты спавна(Устанавливаются командой /ll setspawn)
    x: ''
    y: ''
    z: ''
    yaw: ''
    pitch: ''

## НАТСРОЙКИ СООБЩЕНИЙ ПРИВЕТСТВИЯ И НАЧАЛЬНЫХ КОМАНД
JoinMessage: #Сообщение при входе (%player% - ник игрока)
  Allow: false
  Message:
    - '&d◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼ '
    - '&d◼ '
    - '&d◼  &6Ты в лобби проекта &cLinksMc!'
    - '&d◼ '
    - '&d◼  &cИнформация о проекте ниже &8>>>'
    - '&d◼  &fГруппа ВКонтакте§f: &avk.com/l1nkplay '
    - '&d◼  &fПокупка доната на сайте&f: &bLinksPlugins.com '
    - '&d◼  &fВыбор сервера&f: &e/menu  '
    - '&d◼  '
    - '&d◼  &b(Изменить можно в plugins/LobbyMaster/config.yml)  '
    - '&d◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼ '

JoinCommands:
  Ticks: "20" # Задержка выполнения(в тиках, 1s = 20tics) | НЕ РЕКОМЕНДУЕТСЯ МЕНЯТЬ!
  Player: # Выполнение команд от лица игрока (%player% - ник игрока)
    Allow: false
    cmd:
      - 'menu'
      - ''
      - ''
  Console: # Выполнение команд от лица консоли (%player% - ник игрока)
    Allow: false
    cmd:
      - 'bc &b(Изменить можно в plugins/LobbyMaster/config.yml)'
      - ''
      - ''

## ДОПОЛНИТЕЛЬНЫЕ ФУНКЦИИ
DonateFly: false # выдача возможности полёта для игрока с правом: LinksLobby.donate
FlyAllow: "&c&lСервер >> &aРежим полета вкл!" #Работает если DonateFly: true (чтобы отключить оповещение - оставьте поле пустым)
NoFly: "&c&lСервер >> &aЧтобы пользоваться полетом купите донат!" #Работает если DonateFly: true (чтобы отключить оповещение - оставьте поле пустым)