name: Build and Release Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package

      - name: Extract version from pom.xml
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Determine the next available version
        id: determine_version
        run: |
          BASE_VERSION=${{ env.VERSION }}
          
          # Remove "v" prefix if it exists
          CLEAN_VERSION=${BASE_VERSION#v}
          
          # Initialize the next version with the current base version
          NEXT_VERSION=$CLEAN_VERSION
          
          # Split version into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"
          PATCH=${PATCH:-0}
          
          # Loop to find the next available patch version
          while git rev-parse "v$MAJOR.$MINOR.$PATCH" >/dev/null 2>&1; do
            PATCH=$((PATCH + 1))
          done

          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          FINAL_VERSION="v$NEXT_VERSION"

          echo "FINAL_VERSION=$FINAL_VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.FINAL_VERSION }}
          release_name: ${{ env.FINAL_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload .jar to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/LobbyMaster-${{ env.FINAL_VERSION }}-shaded.jar
          asset_name: LobbyMaster-${{ env.FINAL_VERSION }}.jar
          asset_content_type: application/java-archive
